# YOUR NAME OR TITLE OF YOUR SITE
name: Aiden Vigue

# YOUR BRAND/PERSONAL TAGLINE
tagline: I'm a freshman at Purdue studying Computer Science with a focus on projects related to embedded engineering.

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/acvigue.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # LINKEDIN
  - Name: aidenvigue
    URL: https://www.linkedin.com/in
    Username: aiden-vigue-158891209
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # GITHUB
  - Name: acvigue
    URL: http://github.com
    Username: acvigue
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: aiden@vigue.me
    URL: 'mailto:aiden@vigue.me'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # CUSTOM LINK
  - Name: vigue.me
    URL: https://vigue.me
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
