# YOUR NAME OR TITLE OF YOUR SITE
name: Aiden Vigue

# YOUR BRAND/PERSONAL TAGLINE
tagline: computer science 👨‍🔬

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/acvigue.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: aiden.vigue
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: harsh98trivedi
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: acvigue
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:aiden@vigue.me'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # SNAPCHAT
  - Name: Snapchat
    URL: https://www.snapchat.com/add
    Username: 'aidenvigue'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: w3g33ot2c4zxlxtzy15i7ldxi
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # CUSTOM LINK
  - Name: Blog
    URL: https://vigue.me
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
